directories:
  output: release
  buildResources: build
appId: com.sqlpackage.gui
productName: MSSQL Database Migrator
publish:
  - provider: github
    owner: Uzair42
    repo: mssqlDBTransferSqlPackage-gui_
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - package.json
linux:
  target:
    - AppImage
    - deb
  category: Development
  maintainer: Uzair
win:
  target:
    - zip
    - nsis
    - portable
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 33.4.11
